#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "      _____  __________      "
$L "  __ / / _ \/ ___/_  _/__ ___ ___ _"
$L " / // / // / /__  / // -_) - '/  ' \ "
$L " \___/____/\___/ /_/ \__/\_,_/_/_/_/ "
$L "Welcome to Android `getprop ro.build.version.release` / `getprop ro.cm.version`";
