#!/sbin/sh
#      _____  __________      
#  __ / / _ \/ ___/_  _/__ ___ ___ _
# / // / // / /__  / // -_) _ `/  ' \ 
# \___/____/\___/ /_/ \__/\_,_/_/_/_/ 
#
# File system trim at each boot
#
LOG=/cache/trim.log
echo "*** $(date -u +%Y-%m-%d) ***" >> $LOG
fstrim -v /cache >> $LOG
fstrim -v /data >> $LOG
fstrim -v /system >> $LOG
sync
exit 0
